import { nextui } from "@nextui-org/theme";

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./layouts/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-montserrat)", "system-ui", "sans-serif"],
        ztNeueRalewe: ["var(--font-zt-neue-ralewe)", "sans-serif"],
      },
      flexGrow: {
        1: 1,
        2: 2,
      },
    },
  },
  darkMode: "class",
  plugins: [
    nextui({
      prefix: "nextui",
      addCommonColors: false,
      layout: {
        radius: {
          small: "4px",
          medium: "8px",
          large: "12px",
        },
        borderWidth: {
          small: "1px",
          medium: "2px",
          large: "3px",
        },
      },
      themes: {
        "guardian-1": {
          extend: "dark",
          colors: {
            background: "#FF8B00",
            hourglass: "#090E28",
            numbers: "#E2EFF0",
            comingSoon: "#FEC400",
            daysToGo: "#E1EFF0",
            aTaleAwaits: "#FEC400",
            becomePartOfStory: "#FFFFFF",
            buttonBackground: "#FF8B00",
            buttonText: "#1E1E1E",
            modal: "#090E28",
            headingText: "#FFFFFF",
            labelField: "#595959",
            enterHere: "#C7C7C7",
            cta: "#FEC400",
          },
        },
        "going-global-1": {
          extend: "dark",
          colors: {
            background: "#F4F0ED",
            hourglass: "#02A15F",
            numbers: "#F4F0ED",
            comingSoon: "#0B0A07",
            daysToGo: "#F4F0ED",
            aTaleAwaits: "#DCE8DF",
            becomePartOfStory: "#DCE8DF",
            buttonBackground: "#1D1B1B",
            buttonText: "#FFFFFF",
            modal: "#02A15F",
            headingText: "#FFFFFF",
            labelField: "#595959",
            enterHere: "#C7C7C7",
            cta: "#0B0A07",
          },
        },
        "going-global-2": {
          extend: "dark",
          colors: {
            background: "#FFFFFF",
            hourglass: "#05C850",
            numbers: "#F4F0ED",
            comingSoon: "#004DD1",
            daysToGo: "#F4F0ED",
            aTaleAwaits: "#FFFFFF",
            becomePartOfStory: "#FFFFFF",
            buttonBackground: "#1D1B1B",
            buttonText: "#FFFFFF",
            modal: "#05C850",
            headingText: "#FFFFFF",
            labelField: "#595959",
            enterHere: "#C7C7C7",
            cta: "#004DD1",
          },
        },
        "hero-1": {
          extend: "dark",
          colors: {
            background: "#FFFFFF",
            hourglass: "#000000",
            numbers: "#FFFFFF",
            comingSoon: "#EE2326",
            daysToGo: "#FFFFFF",
            aTaleAwaits: "#FFFFFF",
            becomePartOfStory: "#FFFFFF",
            buttonBackground: "#090E28",
            buttonText: "#FFFFFF",
            modal: "#000000",
            headingText: "#FFFFFF",
            labelField: "#595959",
            enterHere: "#C7C7C7",
            cta: "#EE2326",
          },
        },
        vida: {
          extend: "light",
          colors: {
            background: "#FF5310",
            hourglass: "#FFFFFF",
            numbers: "#1D1B1B",
            comingSoon: "#FF5310",
            daysToGo: "#1D1B1B",
            aTaleAwaits: "#1D1B1B",
            becomePartOfStory: "#1D1B1B",
            buttonBackground: "#1D1B1B",
            buttonText: "#FFFFFF",
            modal: "#FFFFFF",
            headingText: "#000000",
            labelField: "#F5F5F5",
            enterHere: "#6B6F80",
            cta: "#FF5310",
          },
        },
        "motorsports-1": {
          extend: "light",
          colors: {
            background: "#2D48B5",
            hourglass: "#FBFBFB",
            numbers: "#01030E",
            comingSoon: "#E22C0B",
            daysToGo: "#01030E",
            aTaleAwaits: "#01030E",
            becomePartOfStory: "#01030E",
            buttonBackground: "#01030E",
            buttonText: "#FBFBFB",
            modal: "#FBFBFB",
            headingText: "#000000",
            labelField: "#F5F5F5",
            enterHere: "#6B6F80",
            cta: "#E22C0B",
          },
        },
        "bravery-1": {
          extend: "dark",
          colors: {
            background: "#5A189A",
            hourglass: "#F72585",
            numbers: "#FDC500",
            comingSoon: "#E7E7E7",
            daysToGo: "#FFFFFF",
            aTaleAwaits: "#FFFFFF",
            becomePartOfStory: "#000000",
            buttonBackground: "#FFFFFF",
            buttonText: "#5A189A",
            modal: "#F72585",
            headingText: "#FFFFFF",
            labelField: "#595959",
            enterHere: "#C7C7C7",
            cta: "#E7E7E7",
          },
        },
      },
    }),
  ],
};
